export const QUOTES: string[] = [
  "Peace comes from within. Do not seek it without.",
  "No one saves us but ourselves. No one can and no one may.",
  "Three things cannot be long hidden: the sun, the moon, and the truth.",
  "Every morning we are born again. What we do today is what matters most.",
  "Health is the greatest gift, contentment the greatest wealth.",
  "Radiate boundless love towards the entire world.",
  "Your worst enemy cannot harm you as much as your own unguarded thoughts.",
  "To understand everything is to forgive everything.",
  "Nothing is permanent. Everything is subject to change.",
  "Attachment is the root of suffering.",
  "The mind is everything. What you think, you become.",
  "Holding on to anger is like drinking poison and expecting the other to die.",
  "If you light a lamp for someone else, it will also brighten your path.",
  "Let go of what has passed. Let go of what may come. Let go of what is happening now.",
  "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.",
  "You yourself, as much as anybody in the entire universe, deserve your love and affection.",
  "There is no path to happiness: happiness is the path.",
  "Better than a thousand hollow words is one word that brings peace.",
  "Just as a candle cannot burn without fire, men cannot live without a spiritual life.",
  "Pain is certain, suffering is optional.",
  "What we think, we become.",
  "A jug fills drop by drop.",
  "It is better to travel well than to arrive.",
  "In the end only three things matter: how much you loved, how gently you lived, and how gracefully you let go.",
  "Be a lamp unto yourself.",
  "When the mind is pure, joy follows like a shadow that never leaves.",
  "Silence the angry man with love. Silence the ill-natured man with kindness.",
  "Conquer anger with non-anger. Conquer badness with goodness.",
  "Believe nothing, no matter where you read it, unless it agrees with your own reason.",
  "The trouble is, you think you have time.",
  "Wear your ego like a loose-fitting garment.",
  "Each morning we are born again. What we do today matters most.",
];
